export const educationPhotos = [
  {
    id: "sainik",
    name: "Sainik School, Amaravathinagar",
    ja: "サイニック・スクール、アマラヴァティナガル",
    short: "Sainik School",
    location: "AMARAVATHINAGAR · INDIA",
    src: "/images/education/sainik.jpg",
    alt: "Cadets on parade at Sainik School Amaravathinagar",
    altJa: "サイニック・スクール、アマラヴァティナガルでのパレード",
    caption: "Cadets on parade at the Amaravathinagar campus.",
    captionJa: "アマラヴァティナガル・キャンパスでのパレード。",
    credit: "Sainik School Amaravathinagar",
    source: "https://www.sainikschoolamaravathinagar.edu.in/",
    license: "",
    licenseUrl: "",
    position: "center",
  },
  {
    id: "american",
    name: "The American College",
    ja: "アメリカン・カレッジ",
    short: "American College",
    location: "MADURAI · INDIA",
    src: "/images/education/american-campus.jpg",
    alt: "Red-brick arches and facade at The American College, Madurai",
    altJa: "マドゥライのアメリカン・カレッジの赤レンガのアーチと校舎",
    caption: "The red-brick architecture of The American College, Madurai.",
    captionJa: "マドゥライのアメリカン・カレッジを彩る赤レンガ建築。",
    credit: "Photo supplied by the profile owner",
    source: "/images/education/american-campus.jpg",
    license: "",
    licenseUrl: "",
    position: "center",
  },
  {
    id: "madras",
    name: "Madras Institute of Technology",
    ja: "マドラス工科大学",
    short: "MIT Chennai",
    location: "CHENNAI · INDIA",
    src: "/images/education/madras-entrance.jpg",
    alt: "Entrance gate of Madras Institute of Technology, Chennai",
    altJa: "チェンナイのマドラス工科大学の正門",
    caption: "The entrance to Madras Institute of Technology, Chennai.",
    captionJa: "チェンナイのマドラス工科大学の正門。",
    credit: "Photo supplied by the profile owner",
    source: "/images/education/madras-entrance.jpg",
    license: "",
    licenseUrl: "",
    position: "center",
  },
  {
    id: "shizuoka",
    name: "Shizuoka University",
    ja: "静岡大学",
    short: "Shizuoka",
    location: "HAMAMATSU · JAPAN",
    src: "/images/education/shizuoka-campus.jpg",
    alt: "Campus building and landscaped courtyard at Shizuoka University, Hamamatsu",
    altJa: "静岡大学浜松キャンパスの校舎と緑豊かな広場",
    caption: "A view of Shizuoka University’s Hamamatsu Campus.",
    captionJa: "静岡大学浜松キャンパスの風景。",
    credit: "Shizuoka University · ABP",
    source: "https://www.abp.icsu.shizuoka.ac.jp/images/schoollife/campus/img_ph02.jpg",
    license: "",
    licenseUrl: "",
    position: "center",
  },
  {
    id: "anaheim",
    name: "Anaheim University",
    ja: "アナハイム大学",
    short: "Anaheim",
    location: "AKIO MORITA SCHOOL OF BUSINESS",
    src: "/images/education/anaheim-building.webp",
    alt: "Anaheim University building with its red university sign",
    altJa: "赤い大学名の看板があるアナハイム大学の建物",
    caption: "The Anaheim University building, shown in the selected photograph.",
    captionJa: "選定された写真に写るアナハイム大学の建物。",
    credit: "Photo supplied by the profile owner",
    source: "/images/education/anaheim-building.webp",
    license: "",
    licenseUrl: "",
    position: "center",
  },
  {
    id: "mit",
    name: "Massachusetts Institute of Technology",
    ja: "マサチューセッツ工科大学",
    short: "MIT USA",
    location: "CAMBRIDGE, MASSACHUSETTS · USA",
    src: "/images/education/mit.jpg",
    alt: "The Great Dome at Massachusetts Institute of Technology",
    altJa: "マサチューセッツ工科大学のグレートドーム",
    caption: "The Great Dome, an enduring landmark of MIT.",
    captionJa: "MITを象徴するグレートドーム。",
    credit: "Calvinkrishy · Wikimedia Commons",
    source: "https://commons.wikimedia.org/wiki/File:MIT_Main_Apr09.JPG",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    position: "center",
  },
  {
    id: "stanford",
    name: "Stanford Graduate School of Business",
    ja: "スタンフォード大学経営大学院",
    short: "Stanford GSB",
    location: "STANFORD, CALIFORNIA · USA",
    src: "/images/education/stanford.jpg",
    alt: "Knight Management Center at Stanford Graduate School of Business",
    altJa: "スタンフォード大学経営大学院のナイト・マネジメント・センター",
    caption: "The Knight Management Center, home of Stanford GSB.",
    captionJa: "スタンフォードGSBの拠点、ナイト・マネジメント・センター。",
    credit: "Steve Castillo · Wikimedia Commons",
    source:
      "https://commons.wikimedia.org/wiki/File:Knight_Management_Center.jpg",
    license: "CC BY 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by/3.0/",
    position: "center",
  },
];
