export const GATE_URL = "https://gate-enterprise.praba.chatgpt.site";
export const PILOT_CONTACT = "mailto:raj@innuir.com?subject=GATE%20enterprise%20pilot";

export const gatePitch = {
  en: {
    title: "GATE — Your AI Transformation Command Center",
    summary: "Bring AI projects, evidence and executive decisions into one governed workspace. Explore GATE, a working pilot for enterprise AI transformation.",
    back: "AI learning resources", language: "日本語", switchLabel: "日本語に切り替える",
    eyebrow: "GATE · AI TRANSFORMATION COMMAND CENTER",
    headline: "Lead your AI portfolio with evidence.",
    lead: "GATE brings AI projects, approved knowledge and accountable decisions into one workspace. Give leadership a clearer view of what to advance, what needs intervention and what should pause.",
    expansion: "Governed AI Transformation for Enterprises™",
    contact: "Discuss an enterprise pilot", open: "Open GATE", access: "Restricted preview · authorized access required",
    accessNote: "The current web application is a private owner preview. Contact Rajkumar for a walkthrough and to discuss a pilot; this link does not provide public signup or grant access.",
    visualLabel: "THE REVIEW CYCLE", visualTitle: "From project to decision",
    flow: ["Define the purpose", "Review the evidence", "Challenge the gaps", "Record the decision"],
    visualNote: "A workflow illustration. No live customer data or performance claims.",
    problemLabel: "THE LEADERSHIP QUESTION", problemTitle: "Which AI initiatives deserve the next commitment?",
    problem: "A list of pilots cannot answer that on its own. Leaders need to see the business case, the evidence, the unresolved risks and the person accountable for the next step. GATE gives that review a shared structure.",
    capabilitiesLabel: "IN THE WORKING PILOT", capabilitiesTitle: "A connected workflow for governed AI decisions.",
    capabilities: [
      ["Portfolio oversight", "Maintain project purpose, ownership, stage and strategic portfolio. Bring project context, risks, benefits and saved decisions into the review."],
      ["Evidence with accountability", "Collect versioned sources, define access and require independent human review. Keep the evidence behind a conclusion traceable as it changes."],
      ["An evidence adviser", "Search approved knowledge and request source-linked advice. Bounded agentic research can investigate follow-up questions and report gaps or conflicting evidence."],
      ["Governance gap review", "Screen project evidence against the pilot’s curated ISO/IEC 42001, EU AI Act, privacy and Singapore governance mappings. Surface questions for qualified reviewers."],
      ["Recorded decisions", "Save review outcomes, rationale and accountable actions. Revisit a decision when its project facts, evidence or review context changes."],
      ["Integration foundations", "API and MCP interfaces support scoped access and governed advisory workflows. Organization-owned OpenAI, Claude and Gemini connections are implemented; deployment and live-provider acceptance remain part of pilot setup."],
    ],
    personasLabel: "ONE PORTFOLIO · FIVE PERSPECTIVES", personasTitle: "Give every executive a useful question.",
    personas: [
      ["CFO", "Is the value demonstrated?", "Challenge the baseline, comparator, total cost and benefit assumptions."],
      ["CIO", "Can the enterprise operate it?", "Review data ownership, integration, access and service accountability."],
      ["CEO", "Is this the right commitment?", "Compare strategic value, opportunity cost and the next funding decision."],
      ["CTO", "Does the evidence justify scaling?", "Examine evaluation quality, technical limits, fallback and safe operation."],
      ["Legal", "Which duties and rights apply?", "Establish purpose, affected people, data rights and the specialist reviews still needed."],
    ],
    personasNote: "These are review perspectives. Live application permissions are assigned separately.",
    trainingLabel: "LEARN BEFORE YOU COMMIT", trainingTitle: "Rehearse the portfolio meeting.",
    training: "The separate simulation offers five fictional projects, five executive perspectives and a 12-week learning path. Record a recommendation, explain the evidence and compare discussion notes. Practice stays in the browser and does not change live project records or call an LLM.",
    simulation: "Explore the simulation", manual: "Read the user manual", learningAccess: "Both learning links currently share the application’s restricted access.",
    statusLabel: "A CLEAR VIEW OF READINESS", statusTitle: "A working pilot. A deliberate path to enterprise deployment.",
    todayTitle: "Available to demonstrate", today: "Project and portfolio workflows, evidence review, advisory screening, a source-linked knowledge adviser, scoped API/MCP interfaces and a separate executive simulation are implemented. The current private preview is ready for an owner-led walkthrough.",
    nextTitle: "To validate with each enterprise", next: "Production identity and invitations, hosting region, data residency, customer model connections, integration behavior, retrieval and answer quality, security and recovery require deployment-specific acceptance. An API or MCP interface does not make every enterprise connector ready to use.",
    boundariesTitle: "What GATE does not establish", boundaries: "GATE supports governance review; it does not certify ISO compliance, issue a legal opinion or guarantee regulatory coverage or financial returns. Its current mappings need specialist review and appropriate source rights. It reviews the information supplied to it; it does not continuously audit every enterprise system.",
    roadmap: "Commercial billing and a deployment at www.rajagobalan.com/gate are planned. The application link above is the current private preview. Notion and NotebookLM are optional workflow companions, not prerequisites; turnkey connectors and OpenRAG adoption are not claimed as delivered.",
    closeTitle: "Start with one portfolio review.", close: "Bring a small set of AI initiatives and the decisions your leadership team needs to make. Discuss a pilot that tests the evidence workflow, integration requirements and success criteria in your context.",
    attribution: "GATE — Governed AI Transformation for Enterprises™ · By Rajkumar Rajagobalan",
    edition: "Capability statement reviewed 7 September 2026. Pilot status may change.",
  },
  ja: {
    title: "GATE — AI変革コマンドセンター",
    summary: "AIプロジェクト、根拠資料、経営判断を一つのガバナンス基盤へ。企業のAI変革を支援するGATEのパイロットをご紹介します。",
    back: "知見・ツール", language: "English", switchLabel: "Switch language to English",
    eyebrow: "GATE · AI変革コマンドセンター",
    headline: "根拠に基づいて、AIポートフォリオを導く",
    lead: "GATEは、AIプロジェクト、承認済みの知識、責任ある判断を一つのワークスペースにつなぎます。継続すべき取り組み、介入が必要な課題、一時停止すべき案件を、経営層が検討するための基盤です。",
    expansion: "Governed AI Transformation for Enterprises™",
    contact: "企業向けパイロットを相談", open: "GATEを開く", access: "限定プレビュー · アクセス権が必要です",
    accessNote: "現在のWebアプリは所有者限定のプレビューです。デモやパイロットについてはRajkumarにご相談ください。このリンクから一般登録やアクセス権の取得はできません。",
    visualLabel: "レビューの流れ", visualTitle: "プロジェクトから意思決定へ",
    flow: ["目的を定義する", "根拠をレビューする", "不足を問い直す", "判断を記録する"],
    visualNote: "ワークフローの概念図です。顧客データや実績値ではありません。",
    problemLabel: "経営層への問い", problemTitle: "次の投資や継続判断に値するAI案件はどれか。",
    problem: "パイロットの一覧だけでは判断できません。事業上の根拠、未解決のリスク、次の行動の責任者を確認する必要があります。GATEは、そのレビューに共通の構造を提供します。",
    capabilitiesLabel: "パイロットで実装済み", capabilitiesTitle: "AIの意思決定を、根拠と責任につなぐ。",
    capabilities: [
      ["ポートフォリオの把握", "目的、責任者、段階、戦略ポートフォリオを管理。案件の背景、リスク、便益、保存した判断をレビューに集めます。"],
      ["責任を明確にした根拠管理", "資料を版管理し、アクセス範囲を定め、独立した人によるレビューを行います。結論の根拠を変更後も追跡できます。"],
      ["根拠に基づくアドバイザー", "承認済み知識の検索と、出典付きの助言を支援します。回数を制限したエージェント型調査で追加の問いを検討し、不足や矛盾を提示できます。"],
      ["ガバナンスの不足点レビュー", "ISO/IEC 42001、EU AI Act、プライバシー、シンガポールのガバナンスに関するパイロット用マッピングと照合し、専門家が確認すべき問いを明らかにします。"],
      ["判断の記録", "レビュー結果、理由、責任を伴う行動を保存。案件の事実、根拠、レビューの前提が変わった際に判断を見直します。"],
      ["連携の基盤", "APIとMCPによる権限を限定したアクセスや助言のフローを実装。組織所有のOpenAI、Claude、Geminiの接続機能もありますが、実環境での接続検証は導入時に必要です。"],
    ],
    personasLabel: "一つのポートフォリオ · 五つの視点", personasTitle: "役員それぞれの問いを、同じレビューへ。",
    personas: [
      ["CFO", "価値は実証されているか。", "基準値、比較対象、総費用、便益の仮定を検討します。"],
      ["CIO", "企業として運用できるか。", "データの責任、連携、アクセス、サービスの責任体制を確認します。"],
      ["CEO", "今、注力すべき案件か。", "戦略的価値、機会費用、次の投資判断を比較します。"],
      ["CTO", "拡大を正当化する根拠はあるか。", "評価の質、技術的限界、代替手段、安全な運用を検討します。"],
      ["Legal", "どの義務と権利が関係するか。", "目的、影響を受ける人、データ利用権、必要な専門家レビューを明確にします。"],
    ],
    personasNote: "これらはレビューの視点です。実際のアプリの権限は別途割り当てます。",
    trainingLabel: "判断の前に、練習する", trainingTitle: "ポートフォリオ会議をリハーサル。",
    training: "独立したシミュレーションで、五つの架空プロジェクトと五つの役員視点を使い、12週間の学習に取り組めます。提言と根拠を記録し、解説と比較します。練習記録はブラウザー内に保存され、実案件の更新やLLM呼び出しは行いません。",
    simulation: "シミュレーションを見る", manual: "ユーザーマニュアルを読む", learningAccess: "学習ページも現在はアプリと同じ限定アクセスです。内容は英語です。",
    statusLabel: "準備状況を明確に", statusTitle: "動くパイロットから、企業環境での検証へ。",
    todayTitle: "デモできること", today: "案件とポートフォリオの管理、根拠レビュー、助言的なスクリーニング、出典付きアドバイザー、権限を限定したAPI/MCP、役員向けシミュレーションを実装しています。現在は所有者によるデモをご案内できます。",
    nextTitle: "企業ごとに検証すること", next: "本番の認証と招待、リージョン、データ所在地、顧客モデルの接続、連携動作、検索・回答品質、セキュリティ、復旧は導入環境ごとの受入検証が必要です。APIやMCPがあるだけで、すべての企業システムと接続済みになるわけではありません。",
    boundariesTitle: "GATEが保証しないこと", boundaries: "GATEはガバナンスレビューを支援します。ISO認証、法律上の意見、規制の完全な網羅、投資収益を保証するものではありません。現在のマッピングには専門家の確認と適切な資料利用権が必要です。提供された情報を対象とし、全社システムを常時自動監査するものではありません。",
    roadmap: "商用課金とwww.rajagobalan.com/gateへの配備は計画段階です。上記リンクは現在の限定プレビューです。NotionとNotebookLMは任意の補完ツールであり、必須ではありません。完成済みの専用コネクターやOpenRAG導入を実績として示してはいません。",
    closeTitle: "まず、一度のポートフォリオレビューから。", close: "少数のAI案件と、経営層が判断したい問いをご用意ください。根拠の扱い方、連携要件、成功基準を、自社の状況で確かめるパイロットをご相談いただけます。",
    attribution: "GATE — Governed AI Transformation for Enterprises™ · Rajkumar Rajagobalan",
    edition: "機能記述の確認日：2026年9月7日。パイロットの状況は変わる場合があります。",
  },
} as const;
