"use client";

import React from "react";

interface ArticleBriefProps {
  id: string;
  type: string;
  locale: "en" | "ja";
  props?: {
    titleSuggested?: string;
    descriptionSuggested?: string;
    audience?: string;
    keywords?: string[];
    structure?: string[];
    references?: string[];
  };
}

export default function ArticleBrief({
  id,
  type,
  locale,
  props: extraProps
}: ArticleBriefProps) {
  const titleSuggested = extraProps?.titleSuggested || "Untitled Article Proposal";
  const descriptionSuggested = extraProps?.descriptionSuggested || "No meta description suggested yet.";
  const audience = extraProps?.audience || "General Audience";
  const keywords = extraProps?.keywords || [];
  const structure = extraProps?.structure || [];
  const references = extraProps?.references || [];

  const i18n = {
    en: {
      title: "Content Proposal & Article Brief",
      subtitle: "Writing outline and meta recommendation generated by the Editorial Advisor.",
      metaSection: "Suggested Meta Recommendations",
      metaTitle: "Target Title (SEO)",
      metaDesc: "Meta Summary (SEO)",
      audienceLabel: "Target Audience & Value",
      keywordsLabel: "Primary Search Keywords",
      structureLabel: "Proposed Heading Outline Structure",
      referencesLabel: "Grounded References & Fact Sheets",
      lengthHint: "Target length: ~800 to 1,200 words."
    },
    ja: {
      title: "コンテンツ提案＆記事構成案（ブリーフ）",
      subtitle: "編集アドバイザーによって生成された、執筆構成およびメタデータの推奨推奨事項。",
      metaSection: "推奨メタデータ設定",
      metaTitle: "ターゲットタイトル (SEO)",
      metaDesc: "メタディスクリプション (SEO)",
      audienceLabel: "ターゲット読者層・提供価値",
      keywordsLabel: "想定検索キーワード",
      structureLabel: "推奨される章立て構成案 (H2/H3)",
      referencesLabel: "グラウンディング参照ソース",
      lengthHint: "目安文字数: 日本語約 1,600〜2,400 文字。"
    }
  }[locale];

  return (
    <div 
      className="glass-card" 
      style={{ 
        padding: "2rem", 
        borderRadius: "var(--radius-lg)",
        border: "1px solid var(--color-outline-variant)",
        backgroundColor: "var(--glass-bg)"
      }}
      data-component-id={id}
      data-component-type={type}
    >
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: "1.5rem", borderBottom: "1px solid var(--color-outline-variant)", paddingBottom: "1rem" }}>
        <div>
          <h3 style={{ fontSize: "1.4rem", fontWeight: 700, color: "var(--color-primary)", marginBottom: "0.25rem" }}>
            {i18n.title}
          </h3>
          <p style={{ fontSize: "0.85rem", color: "var(--color-on-surface-variant)", lineHeight: 1.4 }}>
            {i18n.subtitle}
          </p>
        </div>
        <span style={{
          fontSize: "0.75rem",
          fontWeight: 700,
          backgroundColor: "var(--color-primary-container)",
          color: "var(--color-on-primary-container)",
          padding: "0.2rem 0.6rem",
          borderRadius: "var(--radius-xs)"
        }}>
          Draft
        </span>
      </div>

      <div style={{ display: "flex", flexDirection: "column", gap: "1.5rem" }}>
        {/* Suggested Meta Section */}
        <div>
          <h4 style={{ fontSize: "1rem", fontWeight: 700, color: "var(--color-primary)", marginBottom: "0.75rem" }}>
            {i18n.metaSection}
          </h4>
          <div style={{
            padding: "1rem",
            backgroundColor: "var(--color-surface-container-high)",
            borderRadius: "var(--radius-sm)",
            border: "1px solid var(--color-outline-variant)",
            display: "flex",
            flexDirection: "column",
            gap: "0.75rem"
          }}>
            <div>
              <span style={{ fontSize: "0.75rem", fontWeight: 700, color: "var(--color-secondary)" }}>{i18n.metaTitle}</span>
              <div style={{ fontSize: "0.95rem", fontWeight: 600, marginTop: "0.15rem" }}>{titleSuggested}</div>
            </div>
            <div style={{ borderTop: "1px solid var(--color-outline-variant)", paddingTop: "0.5rem" }}>
              <span style={{ fontSize: "0.75rem", fontWeight: 700, color: "var(--color-secondary)" }}>{i18n.metaDesc}</span>
              <div style={{ fontSize: "0.9rem", lineHeight: 1.4, color: "var(--color-on-surface-variant)", marginTop: "0.15rem" }}>{descriptionSuggested}</div>
            </div>
          </div>
        </div>

        {/* Audience */}
        <div>
          <h4 style={{ fontSize: "1rem", fontWeight: 700, color: "var(--color-primary)", marginBottom: "0.5rem" }}>
            {i18n.audienceLabel}
          </h4>
          <p style={{ fontSize: "0.9rem", color: "var(--color-on-surface)", lineHeight: 1.5, margin: 0 }}>
            {audience}
          </p>
        </div>

        {/* Keywords */}
        {keywords.length > 0 && (
          <div>
            <h4 style={{ fontSize: "1rem", fontWeight: 700, color: "var(--color-primary)", marginBottom: "0.5rem" }}>
              {i18n.keywordsLabel}
            </h4>
            <div style={{ display: "flex", flexWrap: "wrap", gap: "0.5rem" }}>
              {keywords.map((kw) => (
                <span key={kw} style={{
                  fontSize: "0.75rem",
                  padding: "0.2rem 0.5rem",
                  borderRadius: "var(--radius-full)",
                  backgroundColor: "var(--color-surface-variant)",
                  color: "var(--color-on-surface-variant)",
                  border: "1px solid var(--color-outline-variant)"
                }}>
                  #{kw}
                </span>
              ))}
            </div>
          </div>
        )}

        {/* Heading Structure */}
        {structure.length > 0 && (
          <div>
            <h4 style={{ fontSize: "1rem", fontWeight: 700, color: "var(--color-primary)", marginBottom: "0.5rem" }}>
              {i18n.structureLabel}
            </h4>
            <div style={{
              display: "flex",
              flexDirection: "column",
              gap: "0.5rem",
              borderLeft: "2px solid var(--color-primary)",
              paddingLeft: "1rem"
            }}>
              {structure.map((heading, idx) => (
                <div key={idx} style={{
                  fontSize: "0.9rem",
                  fontWeight: heading.startsWith("##") ? 700 : 500,
                  color: heading.startsWith("##") ? "var(--color-on-background)" : "var(--color-on-surface-variant)",
                  paddingLeft: heading.startsWith("###") ? "1.5rem" : "0"
                }}>
                  {heading.replace(/^##+\s+/, "")}
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Grounded References */}
        {references.length > 0 && (
          <div>
            <h4 style={{ fontSize: "1rem", fontWeight: 700, color: "var(--color-primary)", marginBottom: "0.5rem" }}>
              {i18n.referencesLabel}
            </h4>
            <ul style={{ margin: 0, paddingLeft: "1.2rem", fontSize: "0.85rem", color: "var(--color-on-surface-variant)", lineHeight: 1.5 }}>
              {references.map((ref, idx) => (
                <li key={idx} style={{ marginBottom: "0.25rem" }}>
                  {ref}
                </li>
              ))}
            </ul>
          </div>
        )}
      </div>

      <div style={{
        marginTop: "1.5rem",
        borderTop: "1px solid var(--color-outline-variant)",
        paddingTop: "0.75rem",
        fontSize: "0.8rem",
        color: "var(--color-on-surface-variant)",
        fontStyle: "italic",
        textAlign: "right"
      }}>
        {i18n.lengthHint}
      </div>
    </div>
  );
}
